Update cd to check for server status.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -18,9 +18,11 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.AWS_RSA_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
+
       - name: Add EC2 Host to Known Hosts
         run: |
           ssh-keyscan -H 3.94.121.132 >> ~/.ssh/known_hosts
+
       - name: Deploy to EC2
         run: |
           ssh -i ~/.ssh/id_rsa -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@3.94.121.132 "
@@ -37,9 +39,17 @@ jobs:
             npx tsc app.ts --outDir dist --esModuleInterop &&
 
             echo 'Starting the server in the background...' &&
-            nohup node /home/ubuntu/ACME-Phase-2/user-interface/dist/app.js > log-$$.log 2>&1 & disown &&
-            echo 'Started...' &&
-            exit
+            nohup node /home/ubuntu/ACME-Phase-2/user-interface/dist/app.js > log-$$.log 2>&1 &
+
+            echo 'Waiting for server to start...' &&
+            sleep 10 &&
+            
+            if curl -s http://localhost:3000 > /dev/null; then
+              echo 'Server started successfully.'
+            else
+              echo 'Server failed to start.' >&2
+              exit 1
+            fi
           "
 
       - name: Clean up SSH key
